services:
  mysql:
    image: mysql:8.0
    container_name: iapwe-biblioteca-bbdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_DATABASE: iapwe-biblioteca-bbdd
      MYSQL_USER: damaso
      MYSQL_PASSWORD: mastercaster
      MYSQL_LOCAL_INFILE: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d    # scripts SQL
      - ./csv:/var/lib/mysql-files            # CSV accesibles para LOAD DATA INFILE
    command: --default-authentication-plugin=mysql_native_password --local-infile=1

volumes:
  mysql_data:
